// data
import { home } from "../data";

// components
import { Card, Section, Button, Grid } from "../components";
import Head from 'next/head';
import Image from 'next/image';

// styles
import { useTheme } from "styled-components";
import styles from "../styles/Home.module.css";

export default function Home() {
  const theme = useTheme();
  return (
    <Section
      bgColor={theme.color.secondary.value}
      padding="2rem 2rem 4rem 2rem"
    >
      <Head>
        <title>Alexis Marroquin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Grid
        width="90%"
        direction="column wrap"
        alignItems="center"
        gap={theme.gap.primary}
      >
        
        <Grid
          direction="column wrap"
          gap={theme.gap.primary}
        >
          <p>{home.titleIntro}</p>
          <h2
            style={{
              color: theme.color.white
            }}
          >{home.title}</h2>
          <h2>{home.subTitle}</h2>
        </Grid>

        <Grid
          border={home.headshot.border}
          borderRadius={home.headshot.borderRadius}
        >
          <Image
            src={home.headshot.src}
            width={home.headshot.width}
            height={home.headshot.height}
            className={styles.headshot}
          />    
        </Grid>
      
        <Grid
          direction="column wrap"
          gap={theme.gap.primary}
        >
          <h5>{home.description}</h5>
        </Grid>

        <Button
          width="100%"
          text={"About"}
        />

        <Button
          width="100%"
          text={"Contact"}
        />

      </Grid>

    
        
    </Section>
  )
}
