// components
import { Grid } from "../components";
import Head from 'next/head';

// widgets
import { LandingSection, ContactSection, SkillsSection, FooterSection } from "../widgets";

export default function Home() {
  
  return (
  <Grid>
    <Head>
      <title>Alexis Marroquin</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <LandingSection/>
    <SkillsSection/>
    <ContactSection/>
    <FooterSection/>

  </Grid>
  )
}
